name: "I'm a GitHub action which Greets you with a random Joke 🤪"
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: equivoque
        uses: Neilblaze/Equivoque@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
